- name: "Core Rulebook"
  code: "PZO1110"
  enabled: true
  aliases:
    - "PFRPG Core"
    - "PRPG Core Rulebook"
    - "Pathfinder RPG Core Rulebook"
- name: "Advanced Player's Guide"
  code: "PZO1115"
  enabled: true
  aliases:
    - "APG"
    - "Pathfinder Roleplaying Game: Advanced Player's Guide"
    - "Pathfinder Roleplaying Game APG"
- name: "Advanced Class Guide"
  enabled: true
  code: "PZO1129"
  aliases:
    - "ACG"
    - "Pathfinder Roleplaying Game: Advanced Class Guide"
    - "Pathfinder Roleplaying Game ACG"
- name: "Adventurer's Guide"
  enabled: true
  code: "PZO1138"
  aliases:
    - "Pathfinder Roleplaying Game: Adventurer's Guide"
- name: "GameMastery Guide"
  enabled: true
  code: "PZO1114"
  aliases:
- name: "Bestiary"
  code: "PZO1112"
  aliases:
    - "Pathfinder RPG Bestiary"
- name: "Bestiary 2"
  code: "PZO1116"
  enabled: true
  aliases:
- name: "Bestiary 3"
  code: "PZO1120"
  enabled: true
  aliases:
- name: "Bestiary 4"
  code: "PZO1127"
  enabled: true
  aliases:
- name: "Bestiary 5"
  code: "PZO1133"
  enabled: true
  aliases:
- name: "Bestiary 6"
  code: "PZO1137"
  enabled: true
  aliases:
- name: "Strategy Guide"
  code: "PZO1128"
  enabled: true
  aliases:
- name: "Occult Adventures"
  code: "PZO1132"
  enabled: true
  aliases:
    - "Pathfinder Roleplaying Game: Occult Adventures"
    - "OGL"
- name: "Pathfinder Unchained"
  code: "PZO1131"
  enabled: true
  aliases:
    - "Pathfinder Roleplaying Game Pathfinder Unchained"
- name: "Ultimate Combat"
  enabled: true
  code: "PZO1118"
  aliases:
    - "Pathfinder Roleplaying Game: Ultimate Combat"
- name: "Ultimate Equipment"
  enabled: true
  code: "PZO1123"
  aliases:
    - "Pathfinder Roleplaying Game: Ultimate Equipment"
- name: "Ultimate Magic"
  enabled: true
  code: "PZO1117"
  aliases:
    - "Pathfinder Roleplaying Game: Ultimate Magic"
    - "PRG:UM"
- name: "Pathfinder Player Companion: Heroes of the High Court"
  code: "PZO9476"
  enabled: true
  aliases:
- name: "The Inner Sea World Guide"
  code: "PZO9226"
  enabled: true
  aliases:
    - "Pathfinder Campaign Setting: The Inner Sea World Guide"
- name: "Inner Sea Gods"
  code: "PZO9267"
  enabled: true
  aliases:
    - "Pathfinder Campaign Setting: Inner Sea Gods"
- name: "Ultimate Wilderness"
  enabled: false
  code: "PZO1140"
  aliases:
    - "Pathfinder Roleplaying Game: Ultimate Wilderness"
    - "PRG:UW"
- name: "Dirty Tactics Toolbox"
  code: "PZO9459"
  enabled: true
  aliases:
    - "Pathfinder Player Companion: Dirty Tactics Toolbox"
    - "PPC:DTT"
- name: "Pathfinder Player Companion: Blood of Shadows"
  code: "PZO9466"
  enabled: true
  aliases:
    - "Blood of Shadows"
    - "PPC:BOS"
- name: "Pathfinder Chronicles – Cheliax: Empire of Devils"
  code: "PZO9407"
  enabled: true
  aliases:
    - "Cheliax: Empire of Devils"
    - "PC:CEOD"
- name: "Ultimate Intrigue"
  enabled: false
  code: "PZO1134"
  aliases:
    - "Pathfinder RPG: Ultimate Intrigue"
    - "Pathfinder Roleplaying Game Ultimate Intrigue"