- name: "Core Rulebook"
  code: "PZO1110"
  aliases:
    - "PFRPG Core"
    - "PRPG Core Rulebook"
    - "Pathfinder RPG Core Rulebook"
- name: "Advanced Player's Guide"
  code: "PZO1115"
  aliases:
    - "APG"
    - "Pathfinder Roleplaying Game: Advanced Player's Guide"
    - "Pathfinder Roleplaying Game APG"
- name: "Advanced Class Guide"
  code: "PZO1129"
  aliases:
    - "ACG"
    - "Pathfinder Roleplaying Game: Advanced Class Guide"
    - "Pathfinder Roleplaying Game ACG"
- name: "Adventurer's Guide"
  code: "PZO1138"
  aliases:
    - "Pathfinder Roleplaying Game: Adventurer's Guide"
- name: "GameMastery Guide"
  code: "PZO1114"
  aliases:
- name: "Bestiary"
  code: "PZO1112"
  aliases:
    - "Pathfinder RPG Bestiary"
- name: "Bestiary 2"
  code: "PZO1116"
  aliases:
- name: "Bestiary 3"
  code: "PZO1120"
  aliases:
- name: "Bestiary 4"
  code: "PZO1127"
  aliases:
- name: "Bestiary 5"
  code: "PZO1133"
  aliases:
- name: "Bestiary 6"
  code: "PZO1137"
  aliases:
- name: "Strategy Guide"
  code: "PZO1128"
  aliases:
- name: "Occult Adventures"
  code: "PZO1132"
  aliases:
    - "Pathfinder Roleplaying Game: Occult Adventures"
    - "OGL"
- name: "Pathfinder Unchained"
  code: "PZO1131"
  aliases:
    - "Pathfinder Roleplaying Game Pathfinder Unchained"
- name: "Ultimate Combat"
  code: "PZO1118"
  aliases:
    - "Pathfinder Roleplaying Game: Ultimate Combat"
- name: "Ultimate Equipment"
  code: "PZO1123"
  aliases:
    - "Pathfinder Roleplaying Game: Ultimate Equipment"
- name: "Ultimate Magic"
  code: "PZO1117"
  aliases:
    - "Pathfinder Roleplaying Game: Ultimate Magic"
    - "PRG:UM"
- name: "Pathfinder Player Companion: Heroes of the High Court"
  code: "PZO9476"
  aliases:
- name: "The Inner Sea World Guide"
  code: "PZO9226"
  aliases:
    - "Pathfinder Campaign Setting: The Inner Sea World Guide"
- name: "Ultimate Wilderness"
  code: "PZO1140"
  aliases:
    - "Pathfinder Roleplaying Game: Ultimate Wilderness"
    - "PRG:UW"