casting_time: "1 standard action"
saving_throw: "Fortitude negates (object)"
spell_resistance: "yes (object)"
id: "spell:decompose_corpse"
name: "Decompose Corpse"
description: "Using this spell, the caster rapidly decomposes the flesh from a single\
  \ corpse of size Huge or smaller, leaving behind a perfectly cleaned skeleton. If\
  \ it is cast on a non-skeletal corporeal undead, the creature takes a –2 penalty\
  \ on all rolls and to its Armor Class and CMD for 1 minute."
prerequisites: ""
components: "V, S, M (a pinch of dried toadstool)"
range: "touch"
targets: "one corpse or corporeal undead"
duration: "instantaneous or 1 minute; see text"
school: "necromancy"
levels:
- class_id: "class:arcanist"
  level: 1
- class_id: "class:cleric"
  level: 1
- class_id: "class:druid"
  level: 1
- class_id: "class:hunter"
  level: 1
- class_id: "class:oracle"
  level: 1
- class_id: "class:sorcerer"
  level: 1
- class_id: "class:warpriest"
  level: 1
- class_id: "class:witch"
  level: 1
- class_id: "class:wizard"
  level: 1
source: "Ultimate Magic"
