casting_time: "1 standard action"
saving_throw: "none"
spell_resistance: "yes"
id: "spell:produce_flame"
name: "Produce Flame"
description: "Flames as bright as a torch appear in your open hand. The flames harm\
  \ neither you nor your equipment."
prerequisites: ""
components: "V, S"
range: "0 ft."
targets: ""
duration: "1 min./level (D)"
school: "evocation [fire]"
levels:
- class_id: "class:druid"
  level: 1
- class_id: "class:hunter"
  level: 1
- class_id: "class:shaman"
  level: 1
source: "PRPG Core Rulebook"
