prerequisite_feats: ""
race_name: ""
completion_benefit: ""
suggested_traits: ""
id: "feat:prodigy"
name: "Prodigy"
type: "GENERAL"
description: ""
prerequisites: ""
benefit: "Choose two Craft, Perform, or Profession skills in any combination (two\
  \ Craft skills, a Craft skill and a Perform skill, and so on). You receive a +2\
  \ bonus on checks with these skills. If you have 10 or more ranks in any one of\
  \ these skills, the bonus increases to +4 for that skill."
normal: ""
special: "You can gain this feat multiple times. Its effects do not stack. Each time\
  \ you take the feat, it applies to two new skills."
source: "Pathfinder Roleplaying Game: Ultimate Magic"
teamwork: false
critical: false
grit: false
style: false
performance: false
racial: false
companion: false
note: ""
goal: ""
multiples: false
