prerequisite_feats: ""
race_name: ""
completion_benefit: ""
suggested_traits: ""
id: "feat:train_plants"
name: "Train Plants"
type: "GENERAL"
description: ""
prerequisites: "Handle Animal 5 ranks, Knowledge (nature) 5 ranks."
benefit: "A character with this feat treats creatures of the plant type with Intelligence\
  \ scores of 3 or lower as animals for the purposes of the Handle Animal skill. Plant\
  \ creatures without an Intelligence score are treated as animals with an Intelligence\
  \ of 1 for these purposes. Ordinary plants lack Wisdom and Charisma scores--they\
  \ aren't creatures and can't be trained."
normal: ""
special: ""
source: "Pathfinder Player Companion: Cohorts and Companions"
teamwork: false
critical: false
grit: false
style: false
performance: false
racial: false
companion: false
note: ""
goal: ""
multiples: false
