caster_level: 1
description: "This +1 cestus of blackened leather is reinforced with strips of dark\
  \ iron over the fingers and cruel spikes along the back of the hand and forearm.\
  \ With a mental command, the wearer can cause a series of cords, chains, and braces\
  \ around the palm to lock a held weapon in place, gaining a +10 bonus to her CMD\
  \ to prevent that weapon from being disarmed. While the cestus is locked in this\
  \ manner, the wearer can't use the hand wearing it to complete the somatic component\
  \ of spells or for skill checks. Locking or unlocking a weapon is a move action.\n\
  If the wearer drops the weapon or is disarmed, regardless of whether the cestus\
  \ was locked, a leather strap attached to the weapon prevents it from moving farther\
  \ than the wielder's square, and the wielder can recover the weapon as a move action.\
  \ As a move action, the wearer can issue a mental command that causes the strap\
  \ to detach from the weapon. As with a weapon cord (Pathfinder RPG Ultimate Equipment\
  \ 75), the wearer cannot otherwise switch to a different weapon in that hand unless\
  \ the strap is detached or cut (a move action or an attack, hardness 1, 5 hp). If\
  \ the strap is damaged or destroyed, the cestus's wearer can spend 1 minute wrapping\
  \ a mundane weapon cord around the cestus, in which case the cestus absorbs the\
  \ weapon cord into itself and the leather strap mends itself completely."
id: "item:cestus_of_security"
item_type: "Weapon"
magic_aura: "faint abjuration"
name: "Cestus of Security"
price: "5305 gp"
slot: "Slotless"
sources:
- "Villain Codex"
weapon_crit_range: "19-20/x2"
weapon_damage: "1d4"
weapon_damage_type: "B and P"
weapon_enhancement_bonus: "+1"
weapon_proficiency_group: "Simple"
weapon_special: "Monk"
weapon_type: "Light"
weight: "2 lbs."
