caster_level: 16
description: "This extravagant ring is heavy with precious jewels. As fashions change\
  \ (or as the wearer's fancy shifts), the wearer can alter the appearance of her\
  \ armor, clothing, and even weaponry at will as a standard action; this change is\
  \ illusory and doesn't affect the actual abilities of gear or weapons (although\
  \ drastic changes in size are beyond the scope of this ability). A ring of splendid\
  \ security's primary purpose, though, is to grant the wearer protection from harm.\
  \ As long as it is worn, the ring grants the wearer a +5 deflection bonus to her\
  \ AC, a +5 resistance bonus on saving throws, and spell resistance 22."
id: "item:ring_of_splendid_security"
item_type: "Ring"
magic_aura: "strong abjuration"
name: "Ring of Splendid Security"
price: "180000 gp"
slot: "Ring"
sources:
- "Curse of the Crimson Throne (PFRPG)"
- "Pathfinder #12: Crown of Fangs"
weight: "–"
