caster_level: 20
description: "This item creates a nondimensional space, a pocket paradise. There the\
  \ rod's possessor and as many as 199 other creatures can stay in complete safety\
  \ for a period of time—up to 200 days divided by the number of creatures affected.\
  \ All fractions are rounded down. In this pocket paradise, creatures don't age,\
  \ and natural healing takes place at twice the normal rate. Fresh water and food\
  \ (fruits and vegetables only) are abundant. The climate is comfortable for all\
  \ creatures present. Activating the rod (a standard action) causes the wielder and\
  \ all creatures touching the rod to be transported instantaneously to the paradise.\
  \ Members of large groups can hold hands or otherwise maintain physical contact,\
  \ allowing all connected creatures in a circle or a chain to be affected by the\
  \ rod. Unwilling creatures get a DC 17 Will save to negate the effect. If an unwilling\
  \ creature succeeds at its save, other creatures beyond that point in a chain can\
  \ still be affected by the rod.\nWhen the rod's effect expires, is dismissed, or\
  \ is dispelled, all the affected creatures instantly reappear in the location they\
  \ occupied when the rod was activated. If something else occupies the space that\
  \ a traveler would be returning to, then his body is displaced a sufficient distance\
  \ to provide the space required for reentry. The rod's possessor can dismiss the\
  \ effect whenever he wishes before the maximum time period expires, but the rod\
  \ can only be activated once per week."
id: "item:rod_of_security"
item_type: "Rod"
magic_aura: "strong conjuration"
name: "Rod of Security"
price: "61000 gp"
slot: "Slotless"
sources:
- "Core Rulebook"
- "Ultimate Equipment"
weight: "5 lbs."
