description: "This specialized gear must be tailored to a specific type of animal.\
  \ A training harness provides a +2 bonus on Handle Animal checks made with an animal\
  \ wearing it."
id: "item:training_harness"
item_type: "Mundane"
name: "Training harness"
price: "10 gp"
slot: "Slotless"
sources:
- "Advanced Race Guide"
weight: "10 lbs."
