arcane_spell_failure_chance: 25
armor_bonus: 5
armor_check_penalty: -4
armor_enhancement_bonus: "+2"
armor_max_dex: 3
armor_type: "Medium"
caster_level: 9
description: "This suit of Large +2 scale mail barding is equipped with leather straps\
  \ and loops suitable for attaching harnesses and leashes. It can fit any Large animal\
  \ or magical beast, though not creatures of any other type. When worn by an animal,\
  \ this armor grants the animal two additional tricks or one general purpose (as\
  \ defined by the Handle Animal skill), determined at the time the armor is created."
id: "item:trained_barding"
item_type: "Armor"
magic_aura: "moderate transmutation"
name: "Trained Barding"
price: "8350 gp"
slot: "Armor"
sources:
- "Armor Master's Handbook"
weight: "30 lbs."
